repos:
# - repo: https://github.com/pre-commit/pre-commit-hooks
#   rev: v2.3.0
#   hooks:
#     - id: check-yaml
#     - id: end-of-file-fixer
#     - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.13
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
# - repo: https://github.com/mwouts/jupytext
#   rev: v1.14.7
#   hooks:
#     - id: jupytext
#       args: [--from, ipynb, --to, qmd]
