project:
  type: website
  output-dir: docs

website:
  title: "Luís Assunção"
  site-url: https://assuncaolfi.github.io
  repo-url: https://github.com/assuncaolfi/site
  description: "My personal website"
  navbar:
    background: light
    foreground: dark
    left:
      - index.qmd
      - blog.qmd
      - icon: rss
        href: blog.xml
      - references.qmd
  search: false

bibliography: references.bib

execute:
  cache: true
  echo: false
  freeze: auto

format:
  html:
    css: styles.css
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Fira+Code&family=Fira+Sans&display=swap" rel="stylesheet">    
    mainfont: Fira Sans
    monofont: Fira Code
    # theme:
    #   light: sandstone
    #   dark: sandstone
    theme: sandstone
    title-block-style: default # plain
