project:
  type: website
  output-dir: docs

website:
  title: "Luís Assunção"
  site-url: https://assuncaolfi.github.io/site
  repo-url: https://github.com/assuncaolfi/site
  description: "My personal website"
  favicon: assets/favicon.png
  navbar:
    background: light
    foreground: dark
    left:
      - text: / About
        href: index.qmd
      - text: / Blog
        href: blog.qmd
      - icon: rss
        href: blog.xml
      # - text: / References
      #   href: references.qmd
  search: false

bibliography: references.bib

execute:
  cache: true
  echo: false
  freeze: auto

format:
  html:
    css: styles.css
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Fira+Code&family=Fira+Sans&display=swap" rel="stylesheet">    
    highlight-style: solarized
    mainfont: Fira Sans
    monofont: Fira Code
    # theme:
    #   light: sandstone
    #   dark: sandstone
    theme: 
      light:
        - solar
        - custom.scss
      # dark:
      #   - solar
    title-block-style: default # plain
