project:
  type: website
  output-dir: docs

website:
  site-url: https://assuncaolfi.github.io/site
  navbar: true
  repo-url: https://github.com/assuncaolfi/site
  # description: "My personal website"
  # favicon: assets/favicon.png
  search: false
  title: "Luís Assunção"

bibliography: references.bib

execute:
  cache: true
  echo: false
  freeze: true

format:
  html:
    citations-hover: false
    citation-location: margin
    code-copy: hover
    code-tools:
      source: repo
    highlight-style: assets/custom.theme.json
    html-table-processing: none
    reference-location: margin
    theme:
      - sandstone
      - assets/custom.scss
    title-block-banner: true
