project:
  type: website
  output-dir: docs

website:
  site-url: https://assuncaolfi.github.io/site
  navbar:
    background: white
  repo-url: https://github.com/assuncaolfi/site
  # description: "My personal website"
  # favicon: assets/favicon.png
  search: false
  title: "<"

bibliography: references.bib

execute:
  cache: true
  echo: false
  freeze: true

format:
  html:
    citations-hover: false
    citation-location: margin
    code-copy: hover
    code-tools:
      source: repo
    linkcolor: "#1f77b4"
    link-external-icon: true
    highlight-style: grayscale
    html-math-method: webtex # webtex
    html-table-processing: none
    mainfont: Latin Modern Roman
    monofont: Latin Modern Mono
    reference-location: margin
    theme:
      - default
      - assets/custom.scss
    title-block-banner: false
