---
title: Curriculum Vitae
subtitle: Luís Assunção
date-modified: today
format:
  html:
    toc: true
  pdf: default
---

[{{< bi envelope-at-fill >}} Email]({{< var email >}}) /
[{{< bi github >}} GitHub]({{< var github >}}) /
[{{< bi linkedin >}} LinkedIn]({{< var linkedin >}}) /
[{{< bi globe-americas >}} Website]({{< var website >}})

_The PDF version of this document might be outdated. Please see the [website
version]({{< var website >}}/cv.html)._

## Employment

### [Hotmart](https://hotmart.com/en)

**Staff Data Scientist | April 2020 - present**

* Developed an in-house AB hierarchical testing framework with optional stopping
* Consulted for and developed randomized controlled trials
* Estimated causal effects in non-randomized experiments
* Estimated pricing elasticity for digital products using multilevel models
* Classified evergreen vs launching sales strategies using hidden state models
* Improved quality of course assigments using Item Response Theory models

### [Oper](https://operdata.com.br)

**Data Scientist | Oct 2018 - March 2020**

* Consulted for companies such as AB InBev and GTB in statistical projects
* Modeled spatial pricing elasticity for beverages using Gaussian Processes
* Estimated revenue attribution in multi-touchpoint marketing campaigns

### [IRIS](https://irisbh.com.br/en/)

**Intern | 2015 - 2017**

* Collected, wrangled and described survey data
* Researched policies to advance human rights in the digital matters

## Education

### B.S in Statistics

**Federal University of Minas Gerais (UFMG) | Belo Horizonte, MG - Brazil | 2017
- 2021**

* Researched and authored a
[reproducible monograph](https://github.com/assuncaolfi/monografia/blob/main/monografia.pdf)
(in portuguese with an abstract in english) on exponential random graphs applied
to epidemiology
* Co-authored [Frequency and burden of neurological manifestations upon
hospital presentation in COVID-19 patients: Findings from a large Brazilian
cohort](https://pubmed.ncbi.nlm.nih.gov/36375382/)

## Examples

### Blog

Posts on data analysis using tools such as Python, `polars`, `pymc`, `pulp`,
`seaborn`:

* [Drafting a fantasy football team](https://assuncaolfi.github.io/site/blog/fantasy-football):
  In this post, I delve into the data for the 2022 season of a brazilian fantasy
  football league, formulate a mixed integer linear program to draft the optimal
  team; and present initial concepts for forecasting player scores using mixed
  effects linear models.

* [Additive aging curve](https://assuncaolfi.github.io/site/blog/aging-curve):
  In this post, I compare empirical, semi-parametric and parametric approaches
  to modeling aging-curve-like non-monotonic relationships using data from a
  verbal working memory test.


### Repositories

* [site](https://github.com/assuncaolfi/site): My website and blog post codes
using Quarto
* [mldc2020](https://github.com/assuncaolfi/mldc2020): Recommendation system and
7th place solution to the Mercado Libre Data Challenge 2020
* [rstanbtm](https://github.com/assuncaolfi/rstanbtm): Biterm Topic Model
implementation in Stan
* [qlm](https://github.com/assuncaolfi/qlm): Generate predictive SQL queries
from linear models in R
* [tophat](https://github.com/assuncaolfi/tophat): Scheduled shell script to
fetch and save fantasy football data

### Others

* [Pod e Dev podcast episode](https://podcasts.apple.com/br/podcast/evolu%C3%A7%C3%A3o-e-perspectivas-futuras-para-intelig%C3%AAncia-artificial/id1666875166?i=1000628439729&l=en-GB),
where I talk (in portuguese) about the challenges in pricing digital products
and causal assumptions we made to overcome these challenges in our model at
Hotmart. We also discuss good and bad use cases for large language models, as
well as how models with 2 parameters can be as useful as models with 200 million
parameters.
